export const COLORS = {
  GRAY_DARK: "rgb(54, 57, 62)",
  GRAY_LIGHT: "rgb(115, 118, 124)",
  WHITE: "rgb(255, 255, 255)",
  RED: "rgba(191, 18, 29, 0.9)",
};

const CONTAINER_WIDTH = 70;
const CONTAINER_HEIGHT = CONTAINER_WIDTH * 0.55;
const CONTANER_BR = CONTAINER_HEIGHT;
const INACTIVE_COLOR = COLORS.GRAY_LIGHT;
const ACTIVE_COLOR = COLORS.RED;

const PADDING = 0.15 * CONTAINER_HEIGHT;

const THUMB_HEIGHT = CONTAINER_HEIGHT - PADDING * 2;
const THUMB_START_WIDTH = THUMB_HEIGHT;
const THUMB_FINAL_WIDTH = THUMB_START_WIDTH * 1.5;
const THUMB_START_TRANSLATION = 0;
const THUMB_FINAL_TRANSLATION = CONTAINER_WIDTH - 2 * PADDING - THUMB_HEIGHT;

export const SIZE = {
  CONTAINER_WIDTH,
  CONTAINER_HEIGHT,
  CONTANER_BR,
  PADDING,
  THUMB_HEIGHT,
  THUMB_START_WIDTH,
  THUMB_FINAL_WIDTH,
  THUMB_START_TRANSLATION,
  THUMB_FINAL_TRANSLATION,
};

export const THEME = { INACTIVE_COLOR, ACTIVE_COLOR };
